version: '3'

services:
  php:
    build:
      context: ./php
    container_name: php
    ports:
      - 9000:9000
    volumes:    # this is the document root, so variable?
      - ./src:/srv/www/api
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/srv/www/api    # document root
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    #volumes:
      #- ./sql/tables.sql:/docker-entrypoint-initdb.d/
    depends_on:
      - php
    environment:      # what if without it?
      #MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
