version: '3'

services:
  php:
    build:
      context: ./php
    container_name: php
    ports:
      - 9000:9000
    volumes:   
      - ./src:/srv/www/api
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 1888:80
    volumes:
      - ./src:/srv/www/api    # document root
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mariadb
    container_name: mariadb
    #ports:
      #- 3306:3306
    #volumes:
      #- ./sql/tables.sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  client:
    image: mariadb
    container_name: client
    depends_on:
      - mysql
    restart: always
    #entrypoint: [ "/bin/bash" ]
    stdin_open: true
    tty: true
    entrypoint: [ "mysql", "-hmysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
